# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 614dd6295261aa414fe969f6fb49800da6c61d2d76a4661c90ab5ed198f07fc008023c9e1f3a837a9e00650d9a249f1c01488bd2097be2fdd3ee37d48ec95cda

test:
  secret_key_base: 870a58c7390f4047d16fa17cbb0ea12c221068b1c6e389b4cd89c653e7821cc35860a67963c32381ed215f828af2e82f5894967bbe49e1707a968b8889eead93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
